version: '3'

services:

  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: vara
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080